services:
  intensivo:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: intensivo
      MONGO_INITDB_ROOT_PASSWORD: secret123456
    ports:
      - 27017:27017